CREATE TABLE user (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(128) NOT NULL,
password VARCHAR(128) NOT NULL,
mail VARCHAR(128) NOT NULL,
status INT(1) NOT NULL DEFAULT 2,
created_at DATETIME,
updated_at DATETIME
)ENGINE=InnoDB DEFAULT CHARACTER SET=utf8;
